routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('master.index');
Route::get('/restaurant', 'FrontendController@restaurant')->name('bakery.front.restaurant');
Route::get('/shop', 'FrontendController@shop')->name('bakery.front.shop');
Route::get('/product-list', 'FrontendController@productlist')->name('products.list');
Route::get('/product-category/{category_id}', 'FrontendController@categoryWiseProduct')->name('category.wise.product');
//for gallery
Route::get('/gallery', 'FrontendController@gallery')->name('bakery.gallery');
Route::get('/about',function (){
    return view('bakery.about');
});

Route::get('/addToCart/{product}', 'CartController@addToCart')->name('cart.add');
Route::get('/shopping-cart', 'CartController@showCart')->name('cart.show');
Route::get('/editing-cart/{id}', 'CartController@editCart')->name('cart.edit');
Route::post('/removing-cart/{product}', 'CartController@destroy')->name('cart.remove');
Route::put('/updating/{product}/{status}', 'CartController@update')->name('cart.update');
Route::get('/checkout', 'CartController@checkout')->name('cart.checkout');
Route::post('/order', 'OrderController@store')->name('order.store');
Route::get('/ordershow', 'OrderController@index')->name('order.index')->middleware('auth');
Route::post('/updatestatus/{id}','OrderController@statusupdate')->name('order.update.status')->middleware('auth');

//Route::post('/customer', 'CustomerController@store')->name('customer.store')->middleware('auth');
//Route::get('/customershow', 'CustomerController@index')->name('home')->middleware('auth');
Route::get('/showdelivery', 'OrderController@showdelivery')->name('order.delivery')->middleware('auth');
Route::get('/showpickup', 'OrderController@showpickup')->name('order.pickup')->middleware('auth');





Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::post('/customer', 'HomeController@store')->name('customer.store')->middleware('auth');

Route::group(['middleware'=>'auth'],function (){
    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::get('/billing-bakery','BillingController@bakery')->name('admin.billing.bakery');
    Route::get('/billing-restaurant','BillingController@restaurant')->name('admin.billing.restaurant');
    Route::get('/bill','BillingController@bill')->name('admin.bakery.bill');
    Route::get('/paid','BillingController@paid')->name('admin.bakery.paid');
    Route::get('/printview/{id}', 'BillingController@printview')->name('admin.billing.print');
    Route::get('/sales','BillingController@sales')->name('admin.sales');
    Route::get('/sales-date','BillingController@salesdata')->name('admin.sales.data');
    //admin Order form
    Route::get('/adminorder','OrderController@adminorder')->name('admin.order');
    Route::post('/adminstore','OrderController@adminstore')->name('admin.store');
    Route::get('/adminunlist','OrderController@adminunpaidlist')->name('admin.list');
    Route::get('/adminlist','OrderController@adminpaidlist')->name('admin.paid.list');
    //gallery
    Route::get('/admin-gallery','FrontendController@admingallery')->name('admin.gallery');
    Route::post('/admin-gallery-store','FrontendController@storegallery')->name('admin.gallery.store');
    Route::get('/admin-gallery-list','FrontendController@listgallery')->name('admin.gallery.list');
    Route::post('/admin-gallery-delete/{id}','FrontendController@deletegallery')->name('admin.gallery.delete');


});
Route::get('register',function (){
    return abort(404);
})->middleware('auth');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $fillable = ['category_id', 'name', 'price', 'image', 'quantity','status'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function order(){
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use Faker\Provider\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(5);
        $categories = Category::all();
        return view('product.index', compact('products'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('status',1)->get();
        return view('product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        
        if (!empty($request->file('product_image'))) {
            $path = base_path() . '/public/image/product/';
            $image = $request->file('product_image');
            $name = uniqid() . '_' . $image->getClientOriginalName();

            if ($image->move($path, $name)) {
                $request->request->add(['image' => $name]);
            }
        } else {
            $request->request->add(['image' => "noimage.png"]);
        }
        Product::create($request->all());
        return redirect()->route('product.index')->with('success', 'Product inserted successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        if (!empty($request->file('product_image'))) {
            $path = public_path() . '/image/product/';
            $image = $request->file('product_image');
            $name = uniqid() . '_' . $image->getClientOriginalName();
            if ($image->move($path, $name)) {
                if (file_exists($path . $product->image))
                    unlink($path . $product->image);

                $request->request->add(['image' => $name]);
            }
            $product->update($request->all());
        }
        $product->update($request->all());
        return redirect()->route('product.index')->with('success', 'Product updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $image_all=product::where('id',$product->id)->first();
        $image=$image_all->image;
        if ($image != "noimage.png"){
            $image_path=public_path('image/product/'.$image);
            $img=unlink($image_path);
            if ($img=TRUE){
                $product->delete();
                return redirect()->route('product.index')->with('error', 'Product deleted successfully');
            }
        }
        else{
            $product->delete();
            return redirect()->route('product.index')->with('error', 'Product deleted successfully');
        }
    }

}

resources/views/product/create.blade.php
@extends('layouts.backend')
@section('title','Create Product')
@section('content')
    <section class="content-header">
        <h1>
            Product Management
        </h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Create product</h3>
                <a href="{{route('product.index')}}" class="btn btn-info"><i class="fa fa-list"></i>List</a>
            </div>
            <div class="box-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{route('product.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="forms-group">
                        <label for="category_id">Category Name</label>
                        <select name="category_id" class="form-control">
                            <option>Select Category</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}({{$category->type}})</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Enter the Name of Product" >
                    </div>
                    <div class="forms-group">
                        <label for="price">Price</label>
                        <input type="number" name="price" class="form-control" min="0" placeholder="Enter the Price of Price">
                    </div>
                    <div class="forms-group">
                        <label for="image">Image</label>
                        <input type="file" name="product_image">
                    </div>
                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="number" name="quantity" id="quantity" class="form-control" placeholder="Enter the Quantity of the Product" min="0">
                    </div>
                    <div class="form-group">
                        <label for="active">Status</label>
                        <input type="radio" name="status"  value="1" id="active"/>Active
                        <input type="radio" name="status"  value="0" id="deactive" checked />DeActive
                    </div>
                    <div class="form-group">
                        <input type="submit" name="save" value="Save Product" class="btn btn-success"/>
                        <input type="submit" name="clear" value="Clear" class="btn btn-danger"/>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.backend')
@section('title','Create Product')
@section('content')
    <section class="content-header">
        <h1>
            Product Management
        </h1>
    </section>>
    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Edit Product</h3>
                <a href="{{route('product.index')}}" class="btn btn-info"><i class="fa fa-list"></i>List</a>
            </div>
            <div class="box-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{route('product.update',$product->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="category_id">Category Id</label>
                        <select name="category_id" class="form-control">
                            <option>Select Category</option>
                            @foreach($categories as $category)
                                @if($category->id == $product->category_id)
                                    <option value="{{$category->id}}"selected>{{$category->name}}</option>
                                @else
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" id="name" value="{{$product->name}}">
                    </div>
                    <div class="forms-group">
                        <label for="price">Price</label>
                        <input type="number" name="price" class="form-control" value="{{$product->price}}">
                    </div>
{{--                    <img src="{{asset('image/product/' .$product->image )}}" width="100" alt="">--}}
                    <div class="forms-group">
                        <label for="image">Image</label>
                        <input type="file" name="product_image" class="form-control" value="{{$product->image}}">
                    </div>
                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="text" name="quantity" id="quantity" class="form-control" placeholder="Enter quantity" value="{{$product->quantity}}">
                    </div>
                    <div class="form-group">
                        <label for="active">Status</label>
                        @if($product->status == 1)
                            <input type="radio" id="active" name="status"  value="{{$product->status}}" checked>Active
                            <input type="radio" id="deactive" name="status" value="0">De Active
                        @else
                            <input type="radio" id="active" name="status"  value="1">Active
                            <input type="radio" id="deactive" name="status" value="{{$product->status}}" checked>De Active
                        @endif
                    </div>

                    <div class="form-group">
                        <input type="submit" name="save" value="Save Product" class="btn btn-success"/>
                        <input type="submit" name="clear" value="Clear" class="btn btn-danger"/>
                    </div>



                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/product/index.blade.php
@extends('layouts.backend')
@section('title','List Product')
@section('content')
    <section class="content-header">
        <h1>
            Product Management
        </h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Lists product</h3>
                <a href="{{route('product.create')}}" class="btn btn-info"><i class="fa fa-plus"></i>Create</a>
            </div>
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{session()->get('success')}}
                </div>
            @endif

            @if(session()->has('error'))
                <div class="alert alert-danger">
                    {{session()->get('error')}}
                </div>
            @endif

            <div class="box-body">
                <table class="table table-border text-center">
                    <thead >
                    <tr >
                        <th>SN</th>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Image</th>
                        <th>Quantity</th>
                        <th>Status</th>
                        <th>Action</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody class="my-auto">
                    @php($i=1)
                    @foreach($products as $product)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$product->category->name}}</td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->category->type}}</td>
                            <td>{{$product->price}}</td>
                            <td><img src="{{asset('image/product/' .$product->image )}}" width="30" height="30" alt=""></td>
                            <td>{{$product->quantity}}</td>
                            <td>
                                @if($product->status == 1)
                                    <label class="label label-success">Active</label>
                                @else
                                    <label class="label label-danger">De active</label>
                                @endif
                            </td>
                            <td>
                                <a href="{{route('product.edit',$product->id)}}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                                <a href="{{route('product.show',$product->id)}}" class="btn btn-info"><i class="fa fa-eye"></i></a>
                            </td>
                            <td>
                                <form action="{{route('product.destroy',$product->id)}}" method="post"  onsubmit="return confirm('Are you sure to delete')">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE"/>
                                    <button class="btn btn-danger"> <i class="fa fa-trash"></i></button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="d-flex justify-content-center align-items-center">
                    <div>{{$products->links()}}</div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/product/show.blade.php
@extends('layouts.backend')
@section('title','Show Product')
@section('content')
    <section class="content-header">
        <h1>
            Product Management
        </h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Show product</h3>
                <a href="{{route('product.create')}}" class="btn btn-info"><i class="fa fa-plus"></i>Create</a>
                <a href="{{route('product.index')}}" class="btn btn-info"><i class="fa fa-plus"></i>List</a>
            </div>
            <div class="box-body">
                <table class="table table-border">
                    <tr>
                        <th>Category Name</th>
                        <td>{{$product->category->name}}</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{$product->name}}</td>
                    </tr>
                    <tr>
                        <th>Price</th>
                        <td>{{$product->price}}</td>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <td>{{$product->image}}</td>
                        <div class="img-wrap">
                            <span class="close">&times;</span>
                            <img class="image" src="{{asset('image/product/'. $product->image )}}" alt={{$product->image}} height="100px" width="100px" style="cursor:pointer">
                        </div>

                    </tr>
                    <tr>
                        <th>Quantity</th>
                        <td>{{$product->quantity}}</td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td>
                            @if($product->status == 1)
                                <label class="label label-success">Active</label>
                            @else
                                <label class="label label-danger">De Active</label>
                            @endif
                        </td>

                    </tr>
                    <tr>
                        <th>Created At</th>
                        <td>{{$product->created_at}}</td>
                    </tr>
                    <tr>
                        <th>Updated At</th>
                        <td>{{$product->updated_at}}</td>
                    </tr>
                </table>
            </div>
        </div>
    </section>
@endsection